[workspace]
resolver = "3"
members = [
    "libtest_experiment",
    "mockall_mock_a_sensor",
    "untested_code",
    # "polish_experiment", # disabled, unmaintained
    "rstest_experiment",
    "injectorpp_experiment"]
