[package]
name = "libtest_experiment"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
# serial_test = "0.6.0" # Disalbed, looks unmaintained

[features]
tedge-test = []
